"""Application-wide constants."""

# Thread
MAX_THREADS_PER_USER = 50
MAX_THREAD_LIST_LIMIT = 50

# Cache
MAX_RAW_PRODUCTS_PER_CACHE = 500
MIN_RAW_PRODUCTS_PER_CACHE = 200
CACHE_KEYWORD_SIMILARITY_THRESHOLD = 0.6

# Search
MAX_SEARCH_RESULTS_RETURNED = 20
MAX_TOOL_ITERATIONS = 3
API_RETRY_ATTEMPTS = 3
API_TIMEOUT_SECONDS = 10.0

# LLM
MAX_CONTEXT_MESSAGES = 8
QUERY_CONTEXT_MESSAGES = 5
DISAMBIGUATION_CONTEXT_MESSAGES = 3
TOOL_CONTEXT_MESSAGES = 8

# Ranking
FEEDBACK_CLICK_BOOST = 0.05
FEEDBACK_LIKE_BOOST = 0.10
FEEDBACK_IGNORE_PENALTY = -0.03

# Diversity
MIN_BRANDS_IN_RESULTS = 3
MAX_SAME_BRAND_PERCENT = 0.40

# Intent labels
INTENT_SEARCH = "search"
INTENT_CHAT = "chat"

# Cache decisions
DECISION_REUSE = "reuse"
DECISION_PARTIAL = "partial"
DECISION_NEW = "new"

# Feedback actions
FEEDBACK_CLICK = "click"
FEEDBACK_LIKE = "like"
FEEDBACK_IGNORE = "ignore"

# Tool names
TOOL_PRODUCT_DETAIL = "product_detail"
TOOL_SEARCH = "search_tool"

# Message roles
ROLE_USER = "user"
ROLE_ASSISTANT = "assistant"
